spring.application.name=Module1Introduction
spring.h2.console.enabled = true
#spring.datasource.url=jdbc:h2:file:C:\Users\soham.lambate\Downloads\Springboot cohort 5.0\radomdb
spring.datasource.username =saunDB
spring.datasource.password=saun123
spring.jpa.hibernate.ddl-auto=update
